services:
  - type: web
    name: atlas-core-api
    runtime: node
    rootDir: server
    plan: free
    region: frankfurt
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && node dist/index.js
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PORT
        value: 4000
      - key: PUBLIC_APP_URL
        value: https://atlas-storefront.onrender.com
      - key: PUBLIC_API_URL
        value: https://atlas-core-api.onrender.com
      - key: PAYMENT_PROVIDER
        value: mock
      - key: PESAPAL_CONSUMER_KEY
        sync: false
      - key: PESAPAL_CONSUMER_SECRET
        sync: false
      - key: PESAPAL_ENV
        value: sandbox
      - key: PESAPAL_CURRENCY
        value: RWF

  - type: web
    name: atlas-storefront
    runtime: static
    rootDir: .
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://atlas-core-api.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
